title: Github & Reproducibility Workshop
author: Ryan Corbett & Jo Lynne Rokita
email: corbettr@chop.edu JROKITA@childrensnational.org
lab_website: https://rokitalab.com
github_username: rokitalab
# Theme and theme options
theme: minima
# Pages to appear in site header.
header_home:
  docs/HOME.md
header_pages:
  - docs/setup_overview.md
  - docs/resources.md