title: Github & Reproducibility Workshop
author: Ryan Corbett & Jo Lynne Rokita
email: corbettr@chop.edu, JROKITA@childrensnational.org
twitter_username:
github_username: rokitalab
# Theme and theme options
theme: minima
# Pages to appear in site header.
header_home:
  HOME.md
header_pages:
  - setup_overview.md